### PR TITLE
Update Readme *Privacy and Security*

### PR DESCRIPTION
**Pull request by orpheus-ui**
I believe it's beneficial to include some security notes here.

### CODE REVIEW

**Comment by syavash** [comment]
@orpheus-ui I suggest creating a new .md file for this and link to this page. The homepage should be a summary. What are your thoughts?

**Comment by orpheus-ui** [comment]
Excellent thought!

**Comment by orpheus-ui** [comment]
Privacy.md included.

**Comment by orpheus-ui** [comment]
Excellent suggestions...
I believe it will be beneficial to establish a "FactCheck" app for false information generally throughout Iran, and it will be wonderful to start it from here (maybe a project idea)
It would be preferable to submit your ideas in this form:
https://github.com/WeAreMahsaAmini/Core/discussions/new?category=ideas

**Pull request merged**
